# Generated by Django 6.0.5 on 2026-05-19 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Full name')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration', models.IntegerField(help_text='Duration in minutes', verbose_name='Duration')),
                ('icon_name', models.CharField(max_length=50, verbose_name='SVG Icon Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Service description')),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Barber name')),
                ('experience', models.CharField(max_length=50, verbose_name='Experience')),
                ('rating', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('photo_URL', models.ImageField(blank=True, null=True, upload_to='barbers/', verbose_name='Photo')),
                ('services', models.ManyToManyField(related_name='barbers', to='booking.service', verbose_name='Barber services')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Customer comment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення запису')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.barber', verbose_name='Barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.customer', verbose_name='Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.service', verbose_name='Selected service')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'unique_together': {('barber', 'date', 'time')},
            },
        ),
    ]
