# Generated by Django 6.0.5 on 2026-05-19 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być wpisany w formacie: '+999999999'. Od 9 do 15 cyfr.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('barber', 'date', 'time'), name='unique_barber_appointment_slot'),
        ),
    ]
