# Generated by Django 6.0.5 on 2026-05-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointment_unique_barber_appointment_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='booking.service', verbose_name='Selected services'),
        ),
    ]
